select * from customer limit 10

--1.Total revenue generated by male vs female customer?

select gender,sum(purchase_amount) as revenue from customer
group by gender

--2.which customer used a discount but still spent the more than avg purchase amount?

select customer_id,purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--3.Which are the top 5 products with the highest avg review rating?

select item_purchased,round(avg(review_rating::numeric),2) as avg_review_rating from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5

--4.compare the avg purchase amounts between standard and express shipping?

select shipping_type,round(avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5.Do subscribed customer spend more? Compare avg spend and total revenue 
--beetween subscription and non-subscriptions.

select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status 
order by avg_spend,total_revenue desc

--6.which 5 products have the highest percentage of purchases with discounts appiled?

select item_purchased,
round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end) / count(*),2)as discount_rate
from customer
group by item_purchased 
order by discount_rate desc
limit 5

--7.segment customer into new,returning,and loyal based on their total 
--no.of previous purchases and show the count of the each segment.

with customer_type as(
select customer_id, previous_purchases,
case
     when previous_purchases = 1 then 'New'
     when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
from customer
)

select customer_segment,count(*) as no_of_customer
from customer_type 
group by customer_segment

--what are the top 3 most purchased products within each category?

with item_counts as (
select item_purchased,category,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc ) as item_rank
from customer 
group by category,item_purchased
)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank <= 4

--9.Are customer who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?

select subscription_status,count(customer_id) from customer
where previous_purchases > 5
group by subscription_status

--10 What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc